export const data = {
  primaryNavigation: [
    {
      title: 'Home',
      slug: '/',
    },
    {
      title: 'Cart',
      slug: '/cart',
    },
    {
      title: 'Orders',
      slug: '/orders',
    },
    ,
    {
      title: 'Checkout',
      slug: '/checkout',
    },
  ],
  cartData: [
    {
      website: 'website001',
      url: 'Paid',
      price: '$250.00',
      keywords: 'Credit Card',
      noOfLinks: 5,
    },
    {
      website: 'website002',
      url: 'Pending',
      price: '$150.00',
      keywords: 'PayPal',
      noOfLinks: 5,
    },
    {
      website: 'website003',
      url: 'Unpaid',
      price: '$350.00',
      keywords: 'Bank Transfer',
      noOfLinks: 5,
    },
    {
      website: 'website004',
      url: 'Paid',
      price: '$450.00',
      keywords: 'Credit Card',
      noOfLinks: 5,
    },
    {
      website: 'website005',
      url: 'Paid',
      price: '$550.00',
      keywords: 'PayPal',
      noOfLinks: 5,
    },
    {
      website: 'website006',
      url: 'Pending',
      price: '$200.00',
      keywords: 'Bank Transfer',
      noOfLinks: 5,
    },
    {
      website: 'website007',
      url: 'Unpaid',
      price: '$300.00',
      keywords: 'Credit Card',
      noOfLinks: 5,
    },
  ],
  dummyLinks: [
    {
      url: 'https://www.amazon.com/dp/B09G3HRMVS',
      website: 'Amazon',
      description: 'A stylish wireless keyboard.',
      price: 29.99,
      keyword: 'keyboard',
    },
    {
      url: 'https://www.flipkart.com/smartphone-case',
      website: 'Flipkart',
      description: 'Durable smartphone case.',
      price: 12.49,
      keyword: 'smartphone',
    },
    {
      url: 'https://www.ebay.com/itm/2548974723',
      website: 'eBay',
      description: 'Vintage wristwatch.',
      price: 50.0,
    },
    {
      url: 'https://www.etsy.com/listing/1014523498',
      website: 'Etsy',
      description: 'Handmade ceramic mug.',
      price: 15.0,
      keyword: 'ceramic',
    },
    {
      url: 'https://www.bestbuy.com/site/product/12345',
      website: 'Best Buy',
      description: 'High-definition smart TV.',
      price: 499.99,
      keyword: 'smart TV',
    },
    {
      url: 'https://www.target.com/p/portable-speaker',
      website: 'Target',
      description: 'Portable Bluetooth speaker.',
      price: 25.99,
    },
    {
      url: 'https://www.walmart.com/ip/laptop-bag',
      website: 'Walmart',
      description: 'Waterproof laptop bag.',
      price: 39.99,
      keyword: 'bag',
    },
    {
      url: 'https://www.apple.com/shop/product/MME73AM/A',
      website: 'Apple',
      description: 'AirPods with charging case.',
      price: 159.0,
    },
    {
      url: 'https://www.nike.com/t/air-force-1',
      website: 'Nike',
      description: 'Classic Air Force 1 shoes.',
      price: 90.0,
      keyword: 'shoes',
    },
    {
      url: 'https://www.adidas.com/us/running-shoes',
      website: 'Adidas',
      description: 'Comfortable running shoes.',
      price: 85.0,
    },
    {
      url: 'https://www.zara.com/us/women-jackets',
      website: 'Zara',
      description: "Trendy women's jacket.",
      price: 49.99,
    },
    {
      url: 'https://www.hm.com/us/product/outerwear',
      website: 'H&M',
      description: 'Casual outerwear for men.',
      price: 39.99,
      keyword: 'outerwear',
    },
    {
      url: 'https://www.bookdepository.com/best-books-2023',
      website: 'Book Depository',
      description: 'Bestselling books of 2023.',
      price: 20.0,
    },
    {
      url: 'https://www.udemy.com/course/javascript-basics',
      website: 'Udemy',
      description: 'Learn JavaScript basics.',
      price: 15.0,
      keyword: 'JavaScript',
    },
    {
      url: 'https://www.coursera.org/specializations/python',
      website: 'Coursera',
      description: 'Python programming specialization.',
      price: 39.99,
      keyword: 'Python',
    },
    {
      url: 'https://www.netflix.com/title/81040344',
      website: 'Netflix',
      description: 'Top-rated drama series.',
      price: 9.99,
    },
    {
      url: 'https://www.spotify.com/us/premium',
      website: 'Spotify',
      description: 'Ad-free music streaming.',
      price: 9.99,
      keyword: 'music',
    },
    {
      url: 'https://www.hulu.com/start',
      website: 'Hulu',
      description: 'Stream your favorite TV shows.',
      price: 7.99,
    },
    {
      url: 'https://www.microsoft.com/en-us/office365',
      website: 'Microsoft',
      description: 'Office 365 subscription.',
      price: 69.99,
      keyword: 'office',
    },
    {
      url: 'https://www.google.com/chrome',
      website: 'Google',
      description: 'Download Google Chrome browser.',
      price: 0.0,
    },
    {
      url: 'https://www.tesla.com/models',
      website: 'Tesla',
      description: 'Electric cars by Tesla.',
      price: 35000.0,
    },
    {
      url: 'https://www.samsung.com/us/smartphones',
      website: 'Samsung',
      description: 'Latest Galaxy smartphones.',
      price: 899.0,
      keyword: 'smartphones',
    },
    {
      url: 'https://www.dell.com/en-us/laptops',
      website: 'Dell',
      description: 'High-performance laptops.',
      price: 1199.0,
    },
    {
      url: 'https://www.hp.com/us-en/laptops',
      website: 'HP',
      description: 'Affordable laptops for students.',
      price: 749.99,
    },
    {
      url: 'https://www.lenovo.com/us/en/laptops',
      website: 'Lenovo',
      description: 'Versatile laptops for work and play.',
      price: 899.0,
      keyword: 'laptops',
    },
    {
      url: 'https://www.asus.com/us/monitors',
      website: 'Asus',
      description: 'Gaming monitors for professionals.',
      price: 199.99,
    },
    {
      url: 'https://www.gopro.com/en/us/cameras',
      website: 'GoPro',
      description: 'Capture stunning action shots.',
      price: 349.99,
      keyword: 'camera',
    },
    {
      url: 'https://www.nikonusa.com/en/Camera-Lenses',
      website: 'Nikon',
      description: 'High-quality camera lenses.',
      price: 799.99,
    },
    {
      url: 'https://www.sony.com/electronics/audio',
      website: 'Sony',
      description: 'Premium audio equipment.',
      price: 249.99,
    },
    {
      url: 'https://www.canon.com/cameras',
      website: 'Canon',
      description: 'Professional-grade DSLR cameras.',
      price: 1299.99,
      keyword: 'DSLR',
    },
  ],
  dummyUsers: [
    {
      name: 'Alice Johnson',
      email: 'alice.johnson@example.com',
      password: '$2b$10$Fc4FrSOB8A2l3Dqj5P4LjebLAJbRonIaJzcgM1vxaFFL/Ppr7tKYi',
      role: 'user',
      isActive: true,
    },
    {
      name: 'Bob Smith',
      email: 'bob.smith@example.com',
      password: '$2b$10$tsn4DXv0j6bdTXaXKHnw/.2GUTx9DX4Q.ihoMj.phf7Strz0M6cCC',
      role: 'admin',
      isActive: true,
    },
    {
      name: 'Charlie Brown',
      email: 'charlie.brown@example.com',
      password: '$2b$10$G8viafK6J8/r701nRWroBOefaNAvcESkpxlU5IisWJKBBqPuSYQs2',
      role: 'user',
      isActive: true,
    },
    {
      name: 'Diana Prince',
      email: 'diana.prince@example.com',
      password: '$2b$10$4rytfdJH8hQyNhDC5IYvmeAWBt6YO8qCu0BBa0pq4OB6Dgt.8xYdW',
      role: 'user',
      isActive: true,
    },
    {
      name: 'Ethan Hunt',
      email: 'ethan.hunt@example.com',
      password: '$2b$10$TqwzorNKIEdY5eR8RQq/LuZSVc6I98/dqA1XUm2pvnqU9C7wNA1rq',
      role: 'user',
      isActive: true,
    },
    {
      name: 'Fiona Gallagher',
      email: 'fiona.gallagher@example.com',
      password: '$2b$10$dTebBCsOGX4whfKIAQvliOFNJYoxIwwdKqUN1JQrGwVYxwjbQb4gG',
      role: 'user',
      isActive: false,
    },
    {
      name: 'George Lucas',
      email: 'george.lucas@example.com',
      password: '$2b$10$.NbAgoEXRdbzXfcroRo3ZOL83jNn3MklENBRoFNBemAVWSxJ3x3kS',
      role: 'admin',
      isActive: true,
    },
    {
      name: 'Hannah Baker',
      email: 'hannah.baker@example.com',
      password: '$2b$10$5/H4qn.E095bQsXKW6IXm.VPtsuvGPOa5dsKvDJ2esZfoNlE.LYiW',
      role: 'user',
      isActive: true,
    },
    {
      name: 'Ian Somerhalder',
      email: 'ian.somerhalder@example.com',
      password: '$2b$10$/IlFZ.ZTZVz.qTV6bnSaU.AK0Fuf/SX6AdARL0l/Ho1nMhwgZ3r0i',
      role: 'user',
      isActive: true,
    },
    {
      name: 'Jessica Jones',
      email: 'jessica.jones@example.com',
      password: '$2b$10$cwnG2FNZkQzOnCgA0UtleOK6TAPI5Jp4wLTWKJiEQQQBggCGfPX3W',
      role: 'user',
      isActive: false,
    },
  ],
  dummyCart: [
    {
      userId: '67cdb288e33e0b0c70d98b1f',
      items: [
        {
          linkId: '67cdb02917aaa8d84643f382',
          quantity: 1,
        },
        {
          linkId: '67cdb02917aaa8d84643f383',
          quantity: 2,
        },
      ],
      totalPrice: 54.97,
      createdAt: '2025-03-09T17:00:45.144+00:00',
      updatedAt: '2025-03-09T17:00:45.144+00:00',
    },
    {
      userId: '67cdb288e33e0b0c70d98b20',
      items: [
        {
          linkId: '67cdb02917aaa8d84643f384',
          quantity: 1,
        },
        {
          linkId: '67cdb02917aaa8d84643f388',
          quantity: 1,
        },
      ],
      totalPrice: 89.99,
      createdAt: '2025-03-09T17:05:45.144+00:00',
      updatedAt: '2025-03-09T17:05:45.144+00:00',
    },
    {
      userId: '67cdb288e33e0b0c70d98b21',
      items: [
        {
          linkId: '67cdb02917aaa8d84643f389',
          quantity: 1,
        },
        {
          linkId: '67cdb02917aaa8d84643f38a',
          quantity: 1,
        },
      ],
      totalPrice: 249,
      createdAt: '2025-03-09T17:10:45.144+00:00',
      updatedAt: '2025-03-09T17:10:45.144+00:00',
    },
    {
      userId: '67cdb288e33e0b0c70d98b22',
      items: [
        {
          linkId: '67cdb02917aaa8d84643f386',
          quantity: 1,
        },
      ],
      totalPrice: 499.99,
      createdAt: '2025-03-09T17:15:45.144+00:00',
      updatedAt: '2025-03-09T17:15:45.144+00:00',
    },
    {
      userId: '67cdb288e33e0b0c70d98b23',
      items: [
        {
          linkId: '67cdb02917aaa8d84643f38b',
          quantity: 1,
        },
        {
          linkId: '67cdb02917aaa8d84643f38c',
          quantity: 2,
        },
      ],
      totalPrice: 184.98,
      createdAt: '2025-03-09T17:20:45.144+00:00',
      updatedAt: '2025-03-09T17:20:45.144+00:00',
    },
    {
      userId: '67cdb288e33e0b0c70d98b24',
      items: [
        {
          linkId: '67cdb02917aaa8d84643f385',
          quantity: 4,
        },
      ],
      totalPrice: 60,
      createdAt: '2025-03-09T17:25:45.144+00:00',
      updatedAt: '2025-03-09T17:25:45.144+00:00',
    },
  ],
}
